manifest_version = "1.0.0"

[library]
name = "test_lib_2"
version = "1.2.3"
dependencies = ["dep1/2.4.6", "dep2/3.5.7"]
short_description = ""
long_description = ""
authors = [
    { name = 'dev name', emai = 'dev.name@email.com' },
    { name = 'another dev', emai = 'another.dev@email.com' },
]
maintainers = [{ name = 'some maintainer', email = 'smaintainer@email.com' }]
tags = ['tag', 'another tag']
readme = "README.md"
license = { file = "license.txt" }
# license = { text = "MIT License" }

[files]
scad_files = ["path/to/file.scad", "glob/pattern/to/some/.scad/files/*"]

[urls]
repository = "github.com/github/example"
homepage = "example.com"
documentation = "example.com"
